---
page-layout: full
title-block-banner: true
---

## Hi, I’m Jueun (Bona) Lee

I’m currently based in Madrid, Spain, and pursuing a Master’s degree in Computational Social Science at Universidad Carlos III de Madrid.

Before returning to academia, I worked as a digital marketing strategist for startups across different parts of the world. That journey led me to a deeper interest in how data can help us understand people, society, and decision-making.

Today, I’m focusing on **data analysis**, **data science**, and **machine learning**. I’m especially interested in combining computational methods with social questions to generate insights that are both analytical and human-centered.

This blog is a space for sharing my projects, reflections, and ongoing learning at the intersection of **data, technology, and society**.

<a href="https://github.com/jueunbonalee" target="_blank" class="btn btn-dark" role="button">GitHub</a> <a href="https://www.linkedin.com/in/jueunbonalee" target="_blank" class="btn btn-primary" role="button">LinkedIn</a>

## Work Experience

-   Marketing Strategy Specialist at Fever (Jul 2023 - Jul 2025)

-   Digital Marketing Manager at MODUBA (Nov 2020 - Jun 2023)

-   Digital Marketing Consultant at Project Nord (Mar 2021 - Oct 2021)

## Skills

-   R, SQL

-   Text mining, Data harvesting (API & Web scraping)
